### ISSUE TITLE
 ngAnnotate initialization failed: missing ; 

### ISSUE THREAD

**Issue by Luxor** [craigburke/angular-annotate-asset-pipeline#10]
grails 2.4.5
java 1.8

since 2.1 release

|Precompiling Assets!
|Processing File 1 of 203 - app/ecs/bulk-update/bulk-update-app.js
.Error 
|
WAR packaging error: ngAnnotate initialization failed: missing ; before statement (file:/C:/Users/tuzoant/.m2/repository/com/craigburke/angular/angular-annotate-asset-pipeline/2.1.2/angular-annotate-asset-pipeline-2.1.2.jar!/ngannotate.js#4254)

**Comment by craigburke** [comment]
@Luxor that's weird. This looks just like #9. I see you're running this on Windows, and are you also running the war command from IntelliJ IDEA?

**Comment by Luxor** [comment]
I've run grails dev run-war on windows

**Comment by craigburke** [comment]
What version of Grails?

**Comment by Luxor** [comment]
2.4.5

**Comment by KerchumA222** [comment]
I have this same issue using 2.3.0 with grails 3.0.9. I also tried using 2.2.0 with the same issue:

Execution failed for task ':assetCompile'.
> missing ; before statement (file:/C:/Users/ajkerchum/.gradle/caches/modules-2/files-2.1/com.craigburke.angular/angular-annotate-asset-pipeline/2.2.0/91822be5b99a17890df51f0a0c404cf22ae66667/angular-annotate-asset-pipeline-2.2.0.jar!/ngannotate.js#4353)

**Comment by arvind-das** [comment]
any updates guys ?

**Comment by craigburke** [comment]
If you could all give 2.4.0 a try it should work with Windows.

**Comment by Luxor** [comment]
Works like a charm. Thank you

**Comment by craigburke** [comment]
WOOHOO!

:tada: :raised_hands: :+1:
