### ISSUE TITLE
Upgrade ng-annotate to match angular 1.5 component declaration

### ISSUE THREAD

**Issue by asteria277** [craigburke/angular-annotate-asset-pipeline#13]
Hello,

I'm trying to convert some directives to Angular 1.5 component declaration, but I noticed that the controller part was not annotated :

`app.component('...', {
    
    templateUrl: '...',

    bindings: {
    },

    controller: function ($http) {
    }
    ...
`

-> $http is not annotated

It seems they added support in ng-annotate 1.1.0

Would it be possible to make a new release of angular-annotate-asset-pipeline with it ?

Thanks a lot,
Eric

**Comment by craigburke** [comment]
Absolutely. I'll do that right now.

**Comment by craigburke** [comment]
Give version 2.4.1 a spin.

**Comment by asteria277** [comment]
Thanks you very much for implemented this change so fast ! I tested it and it works perfectly.
