### ISSUE TITLE
JavaScript files aren't annotated

### ISSUE THREAD

**Issue by bmorlac** [craigburke/angular-annotate-asset-pipeline#2]
Hi Craig,

for some reason my JavasSript files aren't annotated. I did the following:
1. created a vanilla Grails app
2. added 'runtime ":angular-annotate-asset-pipeline:1.0.1"' to BuildConfig
3. created a new file example.js in the assets/javascripts folder
4. added the code from your example to the file:
myApp.controller('IndexController', function($scope) {
    $scope.message = "Hello world"
});
5. ran grails war

When Grails finished creating the war file, I opened the example.js file from the packaged war file and it looked like this:
myApp.controller("IndexController",function(e){e.message="Hello world"})

Do I have to do something else besides adding the plugin as runtime dependency? Btw. I tried both, adding it as runtime and compile dependency. I'm using Grails 2.4.2.

Best regards,
Benjamin

**Comment by jako512** [comment]
I have exact the same problem with latest version 2.1.2 in fresh Grails 2.5.0 project.
I also tried version 1.0.2 - but the problem remains the same.

**Comment by craigburke** [comment]
Hi @jako512 feel free to create a new issue that includes what your build.gradle file looks like.
