### ISSUE TITLE
JavaScript files aren't annotated in Grails 2.5.0

### ISSUE THREAD

**Issue by jako512** [craigburke/angular-annotate-asset-pipeline#8]
Steps to reproduce problem:
1. created a vanilla Grails 2.5.0 app
2. added 'runtime ":angular-annotate-asset-pipeline:2.1.2"' to BuildConfig
3. created a new file example.js in the assets/javascripts folder
4. added the code from your example to the file:

    function IndexController($scope) {
    	$scope.message = "Hello world";
    };

5. ran grails war

When Grails finished creating the war file, I opened the example.js file from the packaged war file and it looked like this:

    function IndexController(a){a.message="Hello world"};

So there is missing injecting that is described in readme:

    IndexController.$inject = ["$scope"];

**Comment by craigburke** [comment]
Sorry, I missed the part about it being a Grails 2.5.0 app (for some reason I read that as 3.0). 

I'll take a look.

**Comment by craigburke** [comment]
@jako512 it actually analyzes the code to determine what gets annotated. So you'll need to add the controller to an angular module for that function to actually be annotated.

Does something like this work for you?
```
function IndexController($scope) {
    $scope.message = "Hello world";
};
angular.module('foo', []).controller('IndexController', IndexController);
```

**Comment by craigburke** [comment]
I should tweak the example code in my README since it is misleading.

**Comment by jako512** [comment]
@craigburke this code does not seem to work either - it stays intact (with disabled minificaiton)

**Comment by craigburke** [comment]
Here's the result for me in a new grails 2.5.0 app:
```
function IndexController(a){a.message="Hello world"}IndexController.$inject=["$scope"];angular.module("foo",[]).controller("IndexController",IndexController);
```

Perhaps I'm missing something. Do you think you could throw your test up on github so I can take a closer look?

**Comment by craigburke** [comment]
@jako512 Unfortunately I can't reproduce this on my end so I'm going to go ahead and close this. 

If you're able to throw up an example project that highlights the issue at some point, I'd love to take a look to try to figure it out.

**Comment by verglor** [comment]
I have tried it again with newer version but the result is the same, please try it again:

Steps to reproduce problem:
1. created a vanilla Grails 2.5.4 app
2. added 'runtime ":angular-annotate-asset-pipeline:2.4.1"' to BuildConfig
3. created a new file example.js in the grails-app/assets/javascripts folder
4. added the code from your example to the file:

```
function IndexController($scope) {
    $scope.message = "Hello world";
};
```
1. ran grailsw war

When Grails finished creating the war file, I opened the example-{digest}.js file from the packaged war file and it looked like this:

```
function IndexController(a){a.message="Hello world"};
```

So there is missing injecting that is described in readme:

```
IndexController.$inject = ["$scope"];
```

**Comment by verglor** [comment]
Example project: https://github.com/jako512/grails-example/tree/angular-annotate-asset-pipeline%238

**Comment by craigburke** [comment]
@jako512 it actually analyses the code and your function isn't being annotated because it's not added to an angular module. 

You'd need to have something like this in order to actually trigger it

```
angular.module('myapp')
    .controller('IndexController', IndexController);
```
