### ISSUE TITLE
WAR packaging error: ngAnnotate initialization failed: missing ; before statement

### ISSUE THREAD

**Issue by neliodv** [craigburke/angular-annotate-asset-pipeline#9]
Using Grails 2.51, asset-pipeline 2.2.3, angular-template-asset-pipeline 2.2.1 and angular-annotate-asset-pipeline 2.1.2

Run normal in development, but when generating WAR file i have getting that error:

...
|Processing File 21 of 108 - sysall48.png
|Processing File 22 of 108 - application.js
.Error 
|
WAR packaging error: ngAnnotate initialization failed: missing ; before statement (file:/C:/Users/N�lio/.m2/repository/com/craigburke/angular/angular-annotate-asset-pipeline/2.1.2/angular-annotate-asset-pipeline-2.1.2.jar!/ngannotate.js#4254)

**Comment by craigburke** [comment]
Do you have the same issue using version 2.2.0?

**Comment by neliodv** [comment]
version 2.2.0 same problem, maybe a issue with a config to do.
I've just created a new Grails 2.5.1 project, make war file and OK, then after edit BuildConfig.groovy to use angular-annotate-pipeline 2.2.0 and the same issue occurs.

plugins {
...
        runtime ':angular-annotate-asset-pipeline:2.2.0'
}

**Comment by craigburke** [comment]
@neliodv hmmmm.... would you mind throwing that test app up on github so I can take a look?

**Comment by neliodv** [comment]
Here https://github.com/neliodv/ttteste

**Comment by craigburke** [comment]
Cool! Thank you! I'll take a look!

**Comment by craigburke** [comment]
@neliodv so the issue is when you run `./grailsw war` right? I can't reproduce it on my end but I see you're using Windows so I'll have to give it a try on a Windows VM.

**Comment by neliodv** [comment]
Worked now! The problem only occurs when I try to generate the WAR using the Intellij IDEA, if run "grails war" in a console window works flawlessly.

**Comment by craigburke** [comment]
Ah cool. Glad it's working for you! :+1:
